### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by awrog** [bitstarr/grav-plugin-markdown-details#1]
Grav version 1.6.19

E_NOTICE - Undefined property: Grav\Plugin\MarkdownDetailsPlugin::$a11y

More details in the [log](https://github.com/bitstarr/grav-plugin-markdown-details/files/4353161/plugin-error.log)

**Comment by bitstarr** [comment]
Can you please test again?

**Comment by awrog** [comment]
Installation goes fine now, thanks!
The plugin works also great.
When I set **a11y** to **true** all entries are expanded and will not collapse

![plugin-behaviour](https://user-images.githubusercontent.com/12153667/77051427-8cd0e780-69cb-11ea-8f50-54b872754761.gif)

**Comment by awrog** [comment]
The documentation misses a closing tag:

```!> [h3] About Charles Darwin```

should be

```!> [h3] About Charles Darwin [/h3]```   ([/h3] added)

**Comment by awrog** [comment]
my config:
```
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
```
